services:
  - type: web
    name: freshshop-app
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/CDWeb-FreshShop-0.0.1.jar
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -XX:+UseContainerSupport -Xmx300m
      - key: PORT
        value: 8080
